services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: scoreboard
      POSTGRES_PASSWORD: scoreboard
      POSTGRES_DB: scoreboard
    ports:
      - "5432:5432"
